# Generated by Django 2.2.4 on 2022-12-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
